ReloadTraderConfigSeconds: 30
DiscordConfig:
  Enable: true
  WebhookUrl: https://discord.com/api/webhooks/1281458281197338646/junxB9J1DfWyrLLXgY6xACyg82U19tL2EIRwVr2VxQ0ntq5tHzda3GVPkxzzg7ADgYNU
  Interval: 1  # in minutes
IbkrConfig:
  RestEndpoint: "https://localhost:5001/v1/api"
  WsEndpoint: "wss://localhost:5001/v1/api/ws"
  Fields: [86, 84]
  TickerList: ["IBIT", "FBTC", "GBTC", "BITB", "ARKB", "BRRR", "EZBC", "HODL", "BTCW", "BTCO"]
  ContractIDList: [677037673, 676783301, 349966059, 677037658, 677037663, 677037676, 676783282, 677037670, 676783288, 677037667]
BinanceConfig:
  ExchangeID: "Binance"
  RestEndpoint: "https://api.binance.com"
  WsEndpoint: "wss://stream.binance.com"
  ApiKey: ""
  SecretKey: ""
  Type: "Spot"
